brew "mas"
brew "direnv"

brew "podman"
brew "podman-compose"

cask "1password-cli"
cask "ghostty"
cask "podman-desktop"
cask "adobe-creative-cloud"
cask "alfred"
cask "discord"
cask "zen"
cask "plex"
cask "obsidian"
cask "iina"
cask "1password"
cask "fantastical"
cask "notion"
cask "zotero"
cask "caffeine"
cask "nikitabobko/tap/aerospace"
cask "scrivener"
cask "obs"
cask "insomnia"
cask "todoist-app"
cask "visual-studio-code"
cask "tailscale"

# mas "Bear", id: 1091189122  # Temporarily disabled - Mac App Store connection issue
mas "CleanMyMac", id: 1339170533
