name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      
      - uses: DeterminateSystems/nix-installer-action@main
      
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check flake
        run: nix flake check --accept-flake-config
      
      - name: Build devShell
        run: nix build --accept-flake-config .#devShells.x86_64-linux.default